### ISSUE TITLE
Is it possible to get ui-grid v3.0.5 distributable files loaded into webjars?

### ISSUE THREAD

**Issue by philwestwell** [webjars/ui-grid#12]
Thinking of files such as ui-grid.min.js rather than the source files.

Thanks

**Comment by jamesward** [comment]
The minified files are in the Classic WebJar: http://www.webjars.org/listfiles/ui-grid/3.0.1

Are you requesting a version bump to `3.0.5`?

**Comment by philwestwell** [comment]
Thanks, James. Ah, yes. I suppose that's what I am requesting. Is that something the code authors have to do?
