### ISSUE TITLE
Error while dynamically adding column defs

### ISSUE THREAD

**Issue by sonthosh** [webjars/ui-grid#9]
The column definition watch function is using the number of columns to set the column definition.

 function columnDefsWatchFunction(n, o) {
        if (n && n !== o) {
          self.grid.options.columnDefs = n;
          self.grid.buildColumns({ orderByColumnDefs: true })
            .then(function(){

```
          self.grid.preCompileCellTemplates();

          self.grid.callDataChangeCallbacks(uiGridConstants.dataChange.COLUMN);
        });
    }
  }
```

**Comment by jamesward** [comment]
You need to file this on the actual library: https://github.com/angular-ui/ng-grid
